/* ONE EMBER · BEAT 11 · The doors close.
   The sea-level, ice, event and camera records are generated from the project's
   sources.  The scene does not remember an earlier scroll position: stateFor(t)
   is the only state that reaches the renderer. */
(function(){"use strict";
var $=function(id){return document.getElementById(id);}, RAD=Math.PI/180, DEG=180/Math.PI;
var D, gl, earth=$("earth"), over=$("over"), ctx=over.getContext("2d"), W=0,H=0,DPR=1, P,U={}, bathy, ice;
var CFG=window.EMBER_CONFIG||{id:11,data:"data/beat11.json",years:[14000,8000]};
var FOV=26, TAN=Math.tan(FOV*RAD/2), cur=0, target=0, running=false, external=null, pixelRatio=+new URLSearchParams(location.search).get("pixelRatio")||2;
function clamp(x,a,b){return x<a?a:x>b?b:x} function ss(x){x=clamp(x,0,1);return x*x*(3-2*x)} function span(t,a,b){return ss((t-a)/(b-a))} function lerp(a,b,f){return a+(b-a)*f} function arc(a,b){var d=b-a;while(d>180)d-=360;while(d<-180)d+=360;return d}
function lookup(a,x){if(x<=a[0][0])return a[0][1];var n=a.length-1;if(x>=a[n][0])return a[n][1];var lo=0,hi=n;while(hi-lo>1){var m=(lo+hi)>>1;if(a[m][0]<=x)lo=m;else hi=m}var p=a[lo],q=a[hi];return lerp(p[1],q[1],(x-p[0])/(q[0]-p[0]))}
function xyz(lon,lat){var c=Math.cos(lat*RAD);return[c*Math.cos(lon*RAD),Math.sin(lat*RAD),c*Math.sin(lon*RAD)]}function add(a,b){return[a[0]+b[0],a[1]+b[1],a[2]+b[2]]}function sub(a,b){return[a[0]-b[0],a[1]-b[1],a[2]-b[2]]}function scale(a,k){return[a[0]*k,a[1]*k,a[2]*k]}function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function norm(a){var l=Math.hypot(a[0],a[1],a[2])||1;return scale(a,1/l)}
var CAM=CFG.cams||[[0,-42,58,2.65,5,70],[.18,-30,62,2.3,7,80],[.34,-120,65,2.9,4,110],[.52,-168,65.5,2.1,17,105],[.70,2.5,54.5,2.85,8,75],[.84,24,43,3.2,6,35],[.93,38,36.5,3.6,6,0],[1,38,36.5,3.6,6,0]];
if(CFG.id===8)CAM=[[0,25,55,4.7,4,45],[.25,45,58,4.8,3,50],[.52,58,60,4.6,3,58],[.68,110,66,4.2,5,64],[.80,125,67,3.8,6,70],[1,170,65,1.35,23,78]];
if(CFG.id===1)CAM=[[0,-25,10,12,2,20],[1,18,5,10,2,42]];
if(CFG.id===2)CAM=[[0,18,3,4.1,7,25],[1,19,4,3.3,9,28]];
if(CFG.id===3)CAM=[[0,29,22,3.5,10,48],[.58,35,30,2.7,15,60],[1,35,31,3.2,8,65]];
if(CFG.id===4)CAM=[[0,99,3,2.2,14,12],[.42,99,3,3.6,9,15],[1,30,10,9,3,40]];
function camAt(t){for(var i=0;i<CAM.length-1;i++)if(t<=CAM[i+1][0]){var a=CAM[i],b=CAM[i+1],f=ss((t-a[0])/(b[0]-a[0]));return{lon:a[1]+arc(a[1],b[1])*f,lat:lerp(a[2],b[2],f),alt:lerp(a[3],b[3],f),pitch:lerp(a[4],b[4],f),bearing:a[5]+arc(a[5],b[5])*f}}return CAM[CAM.length-1]}
function frame(c){var n=xyz(c.lon,c.lat),east=norm(cross(n,[0,1,0])),north=cross(east,n),br=c.bearing*RAD,h=add(scale(north,Math.cos(br)),scale(east,Math.sin(br)),),R=1+c.alt,p=Math.min(c.pitch,Math.asin(1/R)*DEG-.35)*RAD,g=Math.asin(clamp(R*Math.sin(p),-1,1))-p,ns=norm(add(scale(n,Math.cos(g)),scale(h,-Math.sin(g)))),pos=scale(ns,R),fwd=norm(sub(n,pos)),e2=norm(cross(ns,[0,1,0])),n2=cross(e2,ns),hs=add(scale(n2,Math.cos(br)),scale(e2,Math.sin(br))),up=norm(sub(hs,scale(fwd,dot(hs,fwd))));return{pos:pos,fwd:fwd,up:up,right:cross(up,fwd),d:R}}
function iceAt(year){var S=D.ice.slices,best=0;for(var i=0;i<S.length-1;i++)if(year<=S[i].kaBP*1000&&year>=S[i+1].kaBP*1000){best=i;break}var a=S[best],b=S[Math.min(best+1,S.length-1)],f=clamp((a.kaBP*1000-year)/((a.kaBP-b.kaBP)*1000||1),0,1);return{a:a.i,b:b.i,f:f,frac:lerp(a.iceFrac,b.iceFrac,f)}}
function eventT(id){for(var i=0;i<D.events.length;i++)if(D.events[i].id===id){var r=D.events[i].dateRange,spanYears=CFG.years[0]-CFG.years[1];return[(CFG.years[0]-r[0])/spanYears,(CFG.years[0]-r[1])/spanYears]}return[0,0]}
function stateFor(t){t=clamp(t,0,1);var year=lerp(CFG.years[0],CFG.years[1],t),c=camAt(t),i=iceAt(year);if(CFG.id===1)return{t:t,year:year,sea:lookup(D.sea,year),cam:c,ice:i,iceVisible:0,cold:.08,focus:0};if(CFG.id===2)return{t:t,year:year,sea:lookup(D.sea,year),cam:c,ice:i,iceVisible:0,cold:.08,focus:span(t,.10,.48)};if(CFG.id===3)return{t:t,year:year,sea:lookup(D.sea,year),cam:c,ice:i,iceVisible:0,cold:.12,focus:1-span(t,.70,.94)};if(CFG.id===4)return{t:t,year:year,sea:lookup(D.sea,year),cam:c,ice:i,iceVisible:0,cold:span(t,.10,.45)*.72*(1-span(t,.58,.92)),focus:span(t,.08,.35)};if(CFG.id===8){var sungir=eventT("sungir"),yana=eventT("yana-rhs");return{t:t,year:year,sea:lookup(D.sea,year),cam:c,ice:i,iceVisible:0,cold:span(t,.06,.48)*.52,sungir:span(t,sungir[0]-.02,sungir[0]+.02),north:span(t,yana[0],yana[1]),light:span(t,sungir[0]-.02,sungir[0]+.02)}}if(CFG.id===10){var white=eventT("white-sands"),gap=eventT("americas-gap");return{t:t,year:year,sea:lookup(D.sea,year),cam:c,ice:i,cold:0,record:1-span(t,white[1],white[1]+.10)*.78,sweep:span(t,gap[1],.94),loss:0}}if(CFG.id===9)return{t:t,year:year,sea:lookup(D.sea,year),cam:c,ice:i,iceVisible:span(t,1/7,.19),cold:.82,steppe:1,light:1};if(CFG.id===13)return{t:t,year:year,sea:lookup(D.sea,year),cam:c,ice:i,cold:0,ocean:span(t,.04,.92),light:span(t,.04,.92)};if(CFG.id===14)return{t:t,year:year,sea:lookup(D.sea,year),cam:c,ice:i,cold:0,forced:span(t,.06,.36),fan:span(t,.42,.92),light:0};var yd=eventT("younger-dryas"),beringia=eventT("beringia-submerged")[0],dogger=eventT("doggerland-storegga")[0],fertile=eventT("fertile-crescent");return{t:t,year:year,sea:lookup(D.sea,year),cam:c,ice:i,cold:span(t,yd[0],yd[0]+.03)*(1-span(t,yd[1]-.03,yd[1])),beringia:span(t,beringia-.025,beringia+.025),dogger:span(t,dogger-.02,dogger+.02),light:span(t,fertile[0],fertile[1])}}
/* The shared panel expects a light channel. The early-act scenes use focus
   instead, so expose it under both names without adding hidden state. */
var earlyStateFor=stateFor;stateFor=function(t){var s=earlyStateFor(t);if(CFG.id<=4)s.light=s.focus;return s};
function project(F,lon,lat){var p=xyz(lon,lat);if(dot(p,norm(F.pos))<1/F.d)return null;var r=sub(p,F.pos),z=dot(r,F.fwd);if(z<=1e-6)return null;return[W/2+dot(r,F.right)/z/TAN*H/2,H/2-dot(r,F.up)/z/TAN*H/2]}
var V="#version 300 es\nvoid main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);gl_Position=vec4(p*2.-1.,0,1);}";
var Q="#version 300 es\nprecision highp float;out vec4 frag;uniform vec2 uRes;uniform sampler2D uBath,uIce;uniform float uSea,uTan,uCold,uIceA,uIceB,uIceF,uIceOpacity,uScale,uOffset;uniform vec3 uCam,uFwd,uUp,uRight;const float PI=3.14159265359;vec2 ll(vec3 p){return vec2(atan(p.z,p.x),asin(clamp(p.y,-1.,1.)));}float elev(vec2 q){vec3 c=texture(uBath,vec2(q.x/(2.*PI)+.5,.5-q.y/PI)).rgb;return(c.r*255.*256.+c.g*255.)*uScale+uOffset;}float ice(vec2 q,float k){float x=mod(k,8.),y=floor(k/8.);return texture(uIce,(vec2(x,y)+vec2(q.x/(2.*PI)+.5,.5-q.y/PI))/vec2(8.,6.)).r;}void main(){vec2 n=(gl_FragCoord.xy-uRes*.5)/(uRes.y*.5);vec3 d=normalize(uFwd+uRight*n.x*uTan+uUp*n.y*uTan);float b=dot(uCam,d),disc=b*b-(dot(uCam,uCam)-1.);if(disc<0.){vec3 sky=mix(vec3(.045,.068,.105),vec3(.008,.014,.026),clamp(-disc*5.,0.,1.));frag=vec4(mix(sky,vec3(.018,.027,.046),uCold*.55),1);return;}vec3 p=uCam+d*(-b-sqrt(disc));vec2 q=ll(normalize(p));float e=elev(q),a=e-uSea,edge=1.-smoothstep(.4,1.5,abs(a)/max(fwidth(a),.001));vec3 land=mix(vec3(.16,.19,.23),vec3(.40,.42,.43),clamp(e/3500.,0.,1.));vec3 water=mix(vec3(.06,.10,.15),vec3(.012,.024,.045),clamp(-a/2600.,0.,1.));vec3 col=mix(water,land,step(0.,a));col=mix(col,vec3(.90,.89,.85),edge*.78);float ic=mix(ice(q,uIceA),ice(q,uIceB),uIceF);col=mix(col,vec3(.72,.79,.84),smoothstep(.08,.42,ic)*(.45+.45*uCold)*uIceOpacity);float limb=clamp(dot(normalize(p),-d),0.,1.);col*=.50+.50*smoothstep(0.,.36,limb);vec2 uv=gl_FragCoord.xy/uRes;col*=mix(.32,1.,smoothstep(0.,.22,uv.y));frag=vec4(col,1);}";
function image(src){return new Promise(function(ok,no){var x=new Image();x.onload=function(){ok(x)};x.onerror=function(){no(new Error("could not load "+src))};x.src=src})}function shader(t,s){var q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q}function texture(img,unit){var x=gl.createTexture();gl.activeTexture(unit);gl.bindTexture(gl.TEXTURE_2D,x);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB8,gl.RGB,gl.UNSIGNED_BYTE,img);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return x}
function init(){gl=earth.getContext("webgl2",{antialias:true,alpha:false});if(!gl)throw Error("WebGL2 did not start");P=gl.createProgram();gl.attachShader(P,shader(gl.VERTEX_SHADER,V));gl.attachShader(P,shader(gl.FRAGMENT_SHADER,Q));gl.linkProgram(P);if(!gl.getProgramParameter(P,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(P));gl.useProgram(P);["uRes","uBath","uIce","uSea","uTan","uCold","uIceA","uIceB","uIceF","uIceOpacity","uScale","uOffset","uCam","uFwd","uUp","uRight"].forEach(function(n){U[n]=gl.getUniformLocation(P,n)});texture(bathy,gl.TEXTURE0);texture(ice,gl.TEXTURE1);gl.uniform1i(U.uBath,0);gl.uniform1i(U.uIce,1);gl.uniform1f(U.uTan,TAN);gl.uniform1f(U.uScale,D.bathy.scale);gl.uniform1f(U.uOffset,D.bathy.offset)}
function resize(){DPR=Math.min(devicePixelRatio||1,2,pixelRatio);W=innerWidth;H=innerHeight;[earth,over].forEach(function(c){c.width=W*DPR;c.height=H*DPR;c.style.width=W+"px";c.style.height=H+"px"});ctx.setTransform(DPR,0,0,DPR,0,0);gl.viewport(0,0,earth.width,earth.height)}
function label(F,lon,lat,k,v,a){var p=project(F,lon,lat);if(!p||a<.02)return;var x=W-55,y=130+(lat>60?0:48);ctx.strokeStyle="rgba(100,124,153,"+(a*.65)+")";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(x-220,y);ctx.lineTo(x,y);ctx.stroke();ctx.textAlign="right";ctx.font='500 10px "IBM Plex Mono",monospace';ctx.fillStyle="rgba(143,168,196,"+a+")";ctx.fillText(k,x,y-8);ctx.font='400 10px "IBM Plex Mono",monospace';ctx.fillStyle="rgba(100,124,153,"+a+")";ctx.fillText(v,x,y+8)}
function routePoint(path,f){var x=clamp(f,0,1)*(path.length-1),i=Math.min(path.length-2,Math.floor(x)),k=x-i;return[lerp(path[i][0],path[i+1][0],k),lerp(path[i][1],path[i+1][1],k)]}
function glow(F,s){if(CFG.id===13)return;if(CFG.id===14){ancestryFan(s);return}var lon=CFG.id===10?-106.28:CFG.id===9?-168:38,lat=CFG.id===10?32.78:CFG.id===9?64:36.5,a=CFG.id===10?s.record:s.light;if(CFG.id===8){a=Math.max(s.sungir,s.north);if(s.north>0&&D.routes.length){var q=routePoint(D.routes[0].path,s.north);lon=q[0];lat=q[1]}else{lon=40.5;lat=56.18}}if(!a)return;var p=project(F,lon,lat);if(!p)return;ctx.save();ctx.strokeStyle="rgba(232,112,58,"+a+")";ctx.lineWidth=1.2;if(CFG.id===10&&a<.5)ctx.setLineDash([3,3]);ctx.beginPath();ctx.arc(p[0],p[1],7,0,Math.PI*2);ctx.stroke();ctx.fillStyle="rgba(232,112,58,"+a+")";ctx.beginPath();ctx.arc(p[0],p[1],2.2,0,Math.PI*2);ctx.fill();ctx.restore()}
function sweepRoute(F,s){if(CFG.id!==10||!D.routes.length||s.sweep<=0)return;var path=D.routes[0].path,n=Math.floor((path.length-1)*s.sweep);ctx.save();ctx.strokeStyle="rgba(232,112,58,"+(.25+.7*s.sweep)+")";ctx.lineWidth=2;ctx.lineCap="round";ctx.beginPath();for(var i=0;i<=n;i++){var p=project(F,path[i][0],path[i][1]);if(!p)continue;i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1])}ctx.stroke();ctx.setLineDash([5,5]);ctx.strokeStyle="rgba(143,168,196,"+(.4*s.sweep)+")";ctx.beginPath();for(var j=0;j<=Math.min(5,n);j++){var q=project(F,path[j][0],path[j][1]);if(!q)continue;j?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])}ctx.stroke();ctx.restore()}
function northRoute(F,s){if(CFG.id!==8||!D.routes.length||s.north<=0)return;var path=D.routes[0].path,n=Math.max(1,Math.floor((path.length-1)*s.north));ctx.save();ctx.strokeStyle="rgba(232,112,58,"+(.18+.7*s.north)+")";ctx.lineWidth=1.5;ctx.lineCap="round";ctx.setLineDash([3,4]);ctx.beginPath();for(var i=0;i<=n;i++){var p=project(F,path[i][0],path[i][1]);if(!p)continue;i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1])}ctx.stroke();ctx.restore()}
function oceanRoutes(F,s){if(CFG.id!==13)return;ctx.save();ctx.lineCap="round";D.routes.forEach(function(route,index){var amount=span(s.t,index*.09,index*.09+.38);if(amount<=0)return;var n=Math.max(1,Math.floor((route.path.length-1)*amount));ctx.beginPath();for(var i=0;i<=n;i++){var p=project(F,route.path[i][0],route.path[i][1]);if(!p)continue;i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1])}ctx.setLineDash(index%2?[2,5]:[]);ctx.strokeStyle="rgba(232,112,58,"+(.16+.64*amount)+")";ctx.lineWidth=1.1;ctx.stroke()});ctx.restore()}
function ancestryFan(s){if(CFG.id!==14||s.fan<=0)return;var levels=5,spread=s.fan,root=[W*.52,H*.72];ctx.save();ctx.lineCap="round";for(var level=0;level<levels;level++){var count=1<<level;for(var branch=0;branch<count;branch++){var x0=level?W*(.5+(branch-(count-1)/2)*.052*spread):root[0],y0=level?H*(.72-level*.085):root[1],next=1<<(level+1),left=branch*2;for(var child=0;child<2;child++){var x1=W*(.5+((left+child)-(next-1)/2)*.052*spread),y1=H*(.72-(level+1)*.085);ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x1,y1);ctx.strokeStyle="rgba(232,112,58,"+(.12+.42*spread)+")";ctx.lineWidth=1;ctx.stroke()}}}ctx.restore()}
function voice(s){var text;if(CFG.id===1)text="Before there were people, the earth was already in motion.";else if(CFG.id===2)text="Our species emerged across a continent.";else if(CFG.id===3)text="Some early journeys did not endure.";else if(CFG.id===4)text="The ash was real. The old bottleneck story was not.";else if(CFG.id===8){var sungir=eventT("sungir")[0];text=s.t<.20?"As the planet cooled, ice spread across the north and the sea withdrew from the coasts.":s.t<sungir?"Still, people travelled into the cold.":"At Sungir, a child was buried with thousands of ivory beads, each one shaped by hand."}else if(CFG.id===10){var white=eventT("white-sands"),gap=eventT("americas-gap");text=s.t<white[1]?"Far to the south, footprints appeared in the mud of what is now New Mexico. They tell us that people were already there.":s.t<gap[1]?"After that, the evidence falls quiet for thousands of years.":"When the record becomes clear again, people are moving rapidly across two continents."}else if(CFG.id===9)text=s.t<.52?"At the height of the ice age, Beringia was a vast grassland between Asia and North America.":"It was home, not simply a bridge to somewhere else.";else if(CFG.id===13)text=s.t<.20?"Once the seas had settled, people learned to travel them with growing confidence.":s.t<.42?"Canoes crossed the Pacific and Indian Oceans.":s.t<.68?"Other migrations spread across Africa, Europe, Asia, and the Atlantic.":"The movement never stopped. It changed its scale.";else if(CFG.id===14)text=s.t<.42?"In the last five hundred years, migration took on another form: empire, enslavement, expulsion, labour, and flight. Millions moved because they were forced to move.":"Follow any family story far enough back, and it stops being a single line. It opens into a vast human web. Each of us carries a different path through the same deep past.";else{var fertile=eventT("fertile-crescent")[0],beringia=eventT("beringia-submerged")[0],dogger=eventT("doggerland-storegga")[0];text=s.t<fertile?"Then the ice began to melt. The sea rose behind the people who had crossed into new lands.":s.t<beringia?"At the same time, some communities began to settle and cultivate the places where they lived.":s.t<dogger?"Beringia disappeared.":"Doggerland disappeared. The paths that had carried generations forward went under water."}var el=$("voice");if(el.textContent!==text){el.classList.remove("on");el.textContent=text;requestAnimationFrame(function(){el.classList.add("on")})}}
function herds(F){var animals=[[-174,66],[-169,62],[-160,64],[-151,61],[-177,59]];ctx.save();ctx.fillStyle="rgba(143,168,196,.75)";animals.forEach(function(a,i){var p=project(F,a[0],a[1]);if(!p)return;ctx.beginPath();ctx.arc(p[0]+i*3,p[1]+(i%2)*2,2.1,0,6.28);ctx.fill()});ctx.restore()}
function draw(s){var F=frame(s.cam),iceReady=CFG.id!==8&&!(CFG.id===9&&s.iceVisible<.02),iceState=CFG.id===8?"UNAVAILABLE":iceReady?s.ice.frac.toFixed(1)+"%":"ATLAS AT 26 KA";gl.useProgram(P);gl.uniform2f(U.uRes,earth.width,earth.height);gl.uniform1f(U.uSea,s.sea);gl.uniform1f(U.uCold,s.cold||0);gl.uniform1f(U.uIceA,s.ice.a);gl.uniform1f(U.uIceB,s.ice.b);gl.uniform1f(U.uIceF,s.ice.f);gl.uniform1f(U.uIceOpacity,s.iceVisible===undefined?1:s.iceVisible);gl.uniform3fv(U.uCam,F.pos);gl.uniform3fv(U.uFwd,F.fwd);gl.uniform3fv(U.uUp,F.up);gl.uniform3fv(U.uRight,F.right);gl.drawArrays(gl.TRIANGLES,0,3);ctx.clearRect(0,0,W,H);if(CFG.id===8){label(F,40.5,56.18,"SUNGIR","34,000 BP · BEADS",s.sungir);label(F,135.42,70.72,"YANA RHS","33,000–31,000 BP",s.north);northRoute(F,s);ctx.textAlign="right";ctx.font='400 10px "IBM Plex Mono",monospace';ctx.fillStyle="rgba(143,168,196,.8)";ctx.fillText("ICE-6G FIELD · COVERAGE BEGINS 26 KA",W-55,224)}else if(CFG.id===10){label(F,-106.28,32.78,"WHITE SANDS","23,000–21,000 BP",s.record);label(F,-73.2,-41.51,"MONTE VERDE","14,800–14,500 BP",s.sweep);sweepRoute(F,s)}else if(CFG.id===9){label(F,-168,64,"BERINGIA","COLD · DRY · UNGLACIATED",1);if(!iceReady){ctx.textAlign="right";ctx.font='400 10px "IBM Plex Mono",monospace';ctx.fillStyle="rgba(143,168,196,"+(1-s.iceVisible*.8)+")";ctx.fillText("ICE-6G FIELD ENTERS · 26 KA",W-55,224)}herds(F)}else if(CFG.id===13){oceanRoutes(F,s);label(F,-149.4,-17.7,"RAPA NUI","~800 BP",span(s.t,.72,.92));label(F,174.8,-41.2,"AOTEAROA","~700 BP",span(s.t,.78,.96))}else{label(F,-168,65.5,"BERINGIA","LAND BRIDGE UNDERWATER",s.beringia);label(F,2.5,54.5,"DOGGERLAND","LAST ROAD CLOSED",s.dogger)}glow(F,s);voice(s);$("state").innerHTML="<span style='color:#8FA8C4'>SEA LEVEL</span> "+s.sea.toFixed(1)+" M&nbsp;&nbsp;·&nbsp;&nbsp;<span style='color:#8FA8C4'>ICE</span> "+iceState;$("p-time").textContent=s.t.toFixed(4)+" · "+Math.round(s.year).toLocaleString()+" BP";$("p-sea").textContent=s.sea.toFixed(1)+" m";$("p-ice").textContent=iceReady?s.ice.a+" → "+s.ice.b+" · "+(s.ice.f*100).toFixed(0)+"%":"not loaded before 26 ka";$("p-cam").textContent=s.cam.lon.toFixed(1)+"° / "+s.cam.lat.toFixed(1)+"°";$("p-light").textContent=CFG.id===10?((s.record*100).toFixed(0)+"% / "+(s.sweep*100).toFixed(0)+"%"):(CFG.id===8?(s.north*100).toFixed(0)+"% northward":(s.light*100).toFixed(0)+"%")}
/* The integration shell may own t.  In that mode this child neither reads its
   own scroll position nor draws while it is hidden behind another beat. */
function renderAt(t){cur=target=clamp(t,0,1);return draw(stateFor(cur))}
function tick(){if(!running)return;if(external&&!external.active){requestAnimationFrame(tick);return}target=external?external.t:clamp(scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight),0,1);cur+= (target-cur)*.14;draw(stateFor(cur));requestAnimationFrame(tick)}
function hash(s){return[s.year.toFixed(2),s.sea.toFixed(4),(s.cold||0).toFixed(5),s.ice.a,s.ice.b,s.ice.f.toFixed(5),(s.iceVisible===undefined?1:s.iceVisible).toFixed(5),(s.sungir||0).toFixed(5),(s.north||0).toFixed(5),(s.beringia||0).toFixed(5),(s.dogger||0).toFixed(5),(s.light||0).toFixed(5),(s.record||0).toFixed(5),(s.sweep||0).toFixed(5),s.cam.lon.toFixed(4),s.cam.lat.toFixed(4),s.cam.alt.toFixed(4),s.cam.pitch.toFixed(4),s.cam.bearing.toFixed(4)].join("|")}
function purity(){var a=[],b=[];for(var i=0;i<=400;i++)a.push(hash(stateFor(i/400)));for(var j=400;j>=0;j--)b.push(hash(stateFor(j/400)));var ok=a.every(function(x,i){return x===b[400-i]});$("o-purity").innerHTML=(ok?"<span class='ok'>PASS</span>":"<span class='bad'>FAIL</span>")+"\n401 states forward and backward.\n"+(ok?"No channel retained a memory of the scroll.":"The same t returned a different world.");return ok}
function join(){var want=D.finalCamera,got=camAt(1),keys=["lon","lat","alt","pitch","bearing"],ok=!!want&&keys.every(function(k){return got[k]===want[k]});$("o-join").innerHTML=(ok?"<span class='ok'>PASS</span>":"<span class='bad'>FAIL</span>")+"\nBeat 11 ends at "+got.lon.toFixed(1)+"E, "+got.lat.toFixed(1)+"N, altitude "+got.alt.toFixed(2)+".\n"+(ok?"The final tuple is the record consumed by the unroll.":"The scene and its successor disagree about the cut.");return ok}
function boot(v){D=v;init();resize();var presentation=document.createElement("style");presentation.textContent="html.presentation #head,html.presentation #copy,html.presentation #state,html.presentation #ruler,html.presentation #hint,html.presentation #panel{display:none!important}";document.head.appendChild(presentation);addEventListener("resize",resize);addEventListener("keydown",function(e){if(e.key.toLowerCase()==="i")$("panel").classList.toggle("on")});addEventListener("message",function(e){var m=e.data;if(!m||m.type!=="one-ember:external-t")return;if(typeof m.presentation==="boolean")document.documentElement.classList.toggle("presentation",m.presentation);if(typeof m.pixelRatio==="number"){pixelRatio=clamp(m.pixelRatio,.65,2);resize()}external={active:!!m.active,t:clamp(+m.t||0,0,1)};if(external.active)renderAt(external.t)});$("t-purity").onclick=purity;var jb=$("t-join");if(jb)jb.onclick=join;$("load").classList.add("off");running=true;window["EMBER"+CFG.id]={stateFor:stateFor,camAt:camAt,frame:frame,finalCamera:D.finalCamera,purity:purity,join:join,renderAt:renderAt,D:D};tick()}
Promise.all([fetch(CFG.data).then(function(r){return r.json()}),image("../data/bathymetry.png"),image("../data/ice_atlas.png")]).then(function(x){bathy=x[1];ice=x[2];boot(x[0])}).catch(function(e){$("lmsg").textContent=String(e.message||e);$("lmsg").style.color="#E8703A"});
})();

/* Every doors-based beat shares the same parent-facing first-frame contract. */
(function () {
  var script = document.createElement("script");
  script.src = new URL("../film/child-ready.js", location.href).href;
  document.head.appendChild(script);
})();
