"""Build the static, cache-safe Vercel deployment surface for One Ember.

The repository deliberately keeps named Terrain-RGB source fields: validators,
builders and the local no-cache server need an auditable path. Those names are
not safe to cache for a year on a public domain. This builder copies the actual
runtime surface into Vercel's static output, publishes the browser-needed
rasters at content-addressed /terrain URLs, and rewrites only the copied
runtime references. The source tree remains untouched.

Run directly while developing:
    python data/build_vercel_static.py
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / ".vercel" / "output" / "static"

# These are the paths the master film can reach. Source builders, audit tools,
# raw ETOPO input and test scratch are intentionally absent from the public
# artifact. Keep this list explicit: adding a new beat must be a deployment
# decision rather than an accidental recursive upload.
RUNTIME_PATHS = (
    "film", "origins", "slice", "shrink", "steppe", "sweep", "doors",
    "unroll", "flow", "ocean", "epilogue", "story", "data", "storyboard.html",
)

# Every public Terrain-RGB raster. The first seven are used by the Phase 3
# progressive slice; the last three remain active in the unroll and later
# scenes. Paths are source-relative so the digest always describes the exact
# bytes evidence tools inspected.
TERRAIN_SOURCES = (
    "slice/data/bathy_global_overview.png",
    "slice/data/bathy_global_overview.webp",
    "slice/data/bathy_redsea_medium.png",
    "slice/data/bathy_redsea_medium.webp",
    "slice/data/bathy_redsea.png",
    "slice/data/bathy_redsea.webp",
    "slice/data/bathy_sunda_medium.png",
    "slice/data/bathy_sunda_medium.webp",
    "slice/data/bathy_sunda.png",
    "slice/data/bathy_sunda.webp",
    "slice/data/bathy_europe_medium.png",
    "slice/data/bathy_europe_medium.webp",
    "slice/data/bathy_europe.png",
    "slice/data/bathy_europe.webp",
    "slice/data/bathy_global.png",
    "data/bathymetry.png",
    "data/ice_atlas.png",
)

DELIVERY_STEMS = (
    "bathy_global_overview", "bathy_redsea_medium", "bathy_redsea",
    "bathy_sunda_medium", "bathy_sunda", "bathy_europe_medium", "bathy_europe",
)


def ignored(_directory: str, names: list[str]) -> list[str]:
    """Keep local runtimes, raw grids and test scratch out of deployment."""
    blocked = {"raw", "__pycache__", ".venv", ".uv-cache", ".git", ".vercel",
               ".playwright-mcp"}
    return [name for name in names if name in blocked or name.endswith((".pyc", ".pyo"))]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def copy_runtime() -> None:
    """Create a clean deployment surface without modifying any source asset."""
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    for relative in RUNTIME_PATHS:
        source, target = ROOT / relative, OUT / relative
        if source.is_dir():
            shutil.copytree(source, target, ignore=ignored)
        else:
            shutil.copy2(source, target)


def publish_terrain() -> dict[str, str]:
    """Copy each runtime raster under a digest-bearing, immutable URL."""
    terrain = OUT / "terrain"
    terrain.mkdir()
    urls: dict[str, str] = {}
    for relative in TERRAIN_SOURCES:
        source = ROOT / relative
        if not source.is_file():
            raise FileNotFoundError("required runtime terrain source is absent: %s" % source)
        digest = sha256(source)[:16]
        name = "%s.%s%s" % (source.stem, digest, source.suffix.lower())
        target = terrain / name
        shutil.copy2(source, target)
        urls[relative] = "/terrain/" + name

    # Production must have no mutable aliases for public elevation fields. It
    # is safe to remove them only in OUT: every runtime reference below is
    # rewritten to its immutable URL.
    for path in (OUT / "slice" / "data").glob("bathy_*.*"):
        if path.suffix.lower() in {".png", ".webp"}:
            path.unlink()
    for relative in ("data/bathymetry.png", "data/ice_atlas.png"):
        (OUT / relative).unlink()
    return urls


def write_delivery_map(urls: dict[str, str]) -> None:
    fields = {}
    for stem in DELIVERY_STEMS:
        fields[stem] = {
            "webp": urls["slice/data/%s.webp" % stem],
            "png": urls["slice/data/%s.png" % stem],
        }
    text = (
        "/* Generated by data/build_vercel_static.py. Content-addressed terrain\n"
        "   may be cached forever because a source change creates a new URL. */\n"
        "window.EMBER_TERRAIN_ASSETS = Object.freeze(%s);\n"
        % json.dumps(fields, indent=2, sort_keys=True)
    )
    (OUT / "slice" / "data" / "terrain_delivery.js").write_text(text, encoding="utf-8")


def rewrite_runtime_references(urls: dict[str, str]) -> None:
    replacements = {
        "../slice/data/bathy_global.png": urls["slice/data/bathy_global.png"],
        "../data/bathymetry.png": urls["data/bathymetry.png"],
        "../data/ice_atlas.png": urls["data/ice_atlas.png"],
    }
    for relative in ("unroll/unroll.js", "doors/doors.js"):
        path = OUT / relative
        text = path.read_text(encoding="utf-8")
        for old, new in replacements.items():
            text = text.replace(old, new)
        path.write_text(text, encoding="utf-8")


def build() -> Path:
    copy_runtime()
    urls = publish_terrain()
    write_delivery_map(urls)
    rewrite_runtime_references(urls)
    return OUT


if __name__ == "__main__":
    output = build()
    published = list((output / "terrain").iterdir())
    print("Vercel static surface: %s" % output)
    print("  %d immutable terrain objects" % len(published))
